steps:
  - command: yarn install && yarn build && yarn e2e
    plugins:
      - docker#v3.2.0:
          image: mcr.microsoft.com/playwright:v1.47.2-jammy
          workdir: /app
          environment:
            - "BUILDKITE_ANALYTICS_TOKEN=$BUILDKITE_ANALYTICS_TOKEN"
