steps:
  - label: "Print Node.js version"
    command: node -v
    key: node-version

  - label: "Print Yarn version"
    command: yarn -v
    key: yarn-version

  - label: "Install dependencies"
    command: yarn install
    key: install
    depends_on:
      - node-version
      - yarn-version

  - label: "Install Playwright browsers"
    command: yarn playwright install
    key: playwright-install
    depends_on:
      - install

  - label: "Build"
    command: yarn build
    key: build
    depends_on:
      - playwright-install

  - label: "End-to-end test"
    command: yarn e2e
    key: e2e
    depends_on:
      - build
