steps:
  - label: "Print Node.js version"
    command: node -v
    key: node-version

  - label: "Install Yarn"
    command: npm install -g yarn
    key: yarn

  - label: "Install dependencies"
    command: yarn install
    key: install
    depends_on:
      - node-version
      - yarn

  - label: "Install Playwright browsers"
    command: yarn playwright install
    key: playwright-install
    depends_on:
      - install

  - label: "Build"
    command: yarn build
    key: build
    depends_on:
      - playwright-install

  - label: "End-to-end test"
    command: yarn e2e
    key: e2e
    depends_on:
      - build
